<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Python Programming - Numpy Basics

## 1.0 Importing our Library

In [2]:
# We will first import the numpy library, so that we can leverage external functionalities 
# that do not come with python
# 
import numpy as np

## 1.1 Creating Arrays

In [2]:
# Example 1
# Numpy arrays are a type of data structures that hold some benefits over 
# Python lists such as being more compact, faster access in reading 
# and writing items. To get started, we can create a 1 dimension (1D) Array 
# using a Python List as shown below.
#
my_list = [0, 1, 2, 3, 4]
npy_my_list = np.array(my_list)

print(npy_my_list)

[0 1 2 3 4]


In [3]:
# Example 2
# We can also create 1D arrays of zeros and 2D arrays of ones 
# from Numpy builtin functions by;
#
zeros_arr = np.zeros(5)
ones_arr = np.ones([3, 4])

print(zeros_arr)
print(ones_arr)

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# Example 3
# Creating an Array with 3 random values  
# 
rand_arr = np.random.rand(3)

print(rand_arr)

[0.68908977 0.66359728 0.60831838]


In [7]:
# Example 4
# Creating an array with evenly spaced values within a given interval 
# as shown using the Numpy arrange function
# 
even_arr = np.arange(0,6,2)

print(even_arr)

[0 2 4]


In [8]:
# Example 5
# Create a 5 x 5 matix with elements from 1 to 25
#
five_matrix = np.arange(1,26).reshape(5,5)

print(five_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### <font color="green">1.1 Challenges

In [12]:
# Challenge 1
# Create a 2D array matix using the list matr = my_mat = [[0,1,2],[3,4,5]]
# Hint: Learn from Example 2
# 
my_mat = [[0,1,2],[3,4,5]]
list_matr = np.array(my_mat)

print(list_matr)

[[0 1 2]
 [3 4 5]]


In [16]:
# Challenge 2
# Create a 2D array of zeros 
# Hint: Learn from Example 2
#

zeros_arr = np.zeros([3,2])

print(zeros_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [28]:
# Challenge 3
# Create a 2D array of random values
# Hint: Learn from Example 2
#
rand_arr = np.random.random_sample([3,2])

print(rand_arr)

[[0.67767486 0.43468981]
 [0.88406861 0.68807554]
 [0.44363447 0.41473059]]


In [11]:
x = np.array([[0,4,2],[8,6,5],[6,7,8]])
x = np.expand_dims(x,axis = 1)
print(x)
print(x.shape)


[[[0 4 2]]

 [[8 6 5]]

 [[6 7 8]]

 [[6 7 8]]]
(4, 1, 3)


In [15]:
# Challenge 4
# Create a 3D array with values starting 6, stops at 40 with interval of 2
#
three_matrix = np.arange(6,41,2).reshape(2,3,3)
print(three_matrix)

[[[ 6  8 10]
  [12 14 16]
  [18 20 22]]

 [[24 26 28]
  [30 32 34]
  [36 38 40]]]


## 1.2 Attributes and Functions

In [37]:
# We use attributes to access information about a particular array,
# while functions to perform a certain operations to the array. 
# We will learn about attributes and functions in this section of the session.
# First let's generate a 1D array to work with; we will name 
# this attribute attribute_arr as shown below;
# 
attribute_arr = np.random.rand(5)

print(attribute_arr)

[0.21685016 0.59129853 0.18408658 0.57462772 0.70226464]


In [38]:
# Example 1
# Using the max() function
# 
attribute_arr.max()

0.7022646370819626

In [39]:
# Example 2
# Using the min() function 
# 
attribute_arr.min()

0.18408657677189355

In [40]:
# Example 3
# Using the argmax() function to return the indice of the max element of the array 
#
attribute_arr.argmax()

4

In [41]:
# Example 4
# Using the argmin() function to return the indice of the min element of the array
#
attribute_arr.argmin()

2

In [42]:
# Example 5
# Using the shape attribute to find the size of the array
#
attribute_arr.shape

(5,)

### <font color="green">1.2. Challenges</font>

In [54]:
# First generate a 2D array to work with

work = [(4,6),(1,3.0)]
list_work = np.array(work)
print(list_work)


[[4. 6.]
 [1. 3.]]


In [55]:
# Challenge 1
# Then we will find the minimum value of the 2D array
#
list_work.min()

1.0

In [56]:
# Challenge 2
# We will find the maximum value of the 2D array
#
list_work.max()

6.0

In [57]:
# Challenge 3
# Then return the indice of the maximun element of the 2D array 
# 
list_work.argmax()

1

In [58]:
# Challenge 4
# Again return the indice of the minimum element of the 2D array
# 
list_work.argmin()

2

In [59]:
# Challenge 5
# Lastly, return the data type of the generated 2D array using dtype
# 

print(list_work.dtype)


float64


## 1.3  Indexing  and Broadcasting

In [60]:
# Creating an array to work with. The array will be comprised of even numbers from 0 t0 15
in_array = np.arange(0,15,2)

print(in_array)

[ 0  2  4  6  8 10 12 14]


In [61]:
# Example 1
# Bracketing indexing allows us to access
# elements from a Numpy array as shown
# 
print(in_array[2]) # Displays the third element in the list
print(in_array[1:5]) # Displays values from the second element to the fifth element
print(in_array[3:]) # Displays the 4th element to the last element in the list

4
[2 4 6 8]
[ 6  8 10 12 14]


In [68]:
# Example 2
# Arrays with different sizes cannot be added, subtracted or used in any arithmetic.
# one way of solving this is to duplicate the smaller array so that its size is the same as the larger array.
# This process is called broadasting and is available in numpy. 

# Broadcasting is Numpy's terminology for performing mathematical operations 
# between arrays with different shapes. This example provides insights on 
# broadcasting. First, lets run this cell then later uncomment each block trying
# to understand what happens. 
# Once you're done with the final block, you can get a detailed explanation 
# on broadcasting here: http://bit.ly/NumpyBroadcasting
# 

in_array[0:2] = 100
print(in_array)

# First reseting our array i.e. recreating it
in_array = np.arange(0,11)
print(in_array)

# Then making a copy 
in_array_copy = in_array.copy()
print(in_array_copy)

# Afterwards creating a new array upon slicing
slice_of_arr = in_array[0:5]
print(slice_of_arr)

# Changing the Slice
slice_of_arr[:]=22
print(slice_of_arr)

# NB: Changes also occur in our original array
print(in_array)

# check your copy
print(in_array_copy)

[100 100  22  22  22   5   6   7   8   9  10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[22 22 22 22 22]
[22 22 22 22 22  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [72]:
# Example 3
# Indexing a 2D array (matrices)
# 

ind_arr_2d = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print(ind_arr_2d)

# Selecting element at row index 1 & column index 2
#
print(ind_arr_2d[1][2])

# Selecting a Row at index 1
#
row = ind_arr_2d[1]
print(row)

# Selecting a column at index 1 
# 
column = ind_arr_2d[:, 1]
print(column)

[[21 22 23]
 [11 22 33]
 [43 77 89]]
33
[11 22 33]
[22 22 77]


In [77]:
# Example 4 
# Fancy Indexing allows us to select entire rows or columns out of order
# as shown
# 

# First creating an array or zeros
arr2d = np.zeros((10,10))
print(arr2d)

# Length of array
arr_length = arr2d.shape[1]
print(arr_length)

# creating the array 
for i in range(arr_length):
    arr2d[i] = i
    
print(arr2d)

# Now selecting the first, third and the fourth rows via fancy indexing
arr2d[[0,2,3]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
10
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

### <font color="green">1.3. Challenges</font>

In [16]:
# First, we create a 2D array to work with
array_2d = np.array(([15,20,25],[15,20,25],[30,35,40]))
print(array_2d)

[[15 20 25]
 [15 20 25]
 [30 35 40]]


In [79]:
# Challenge 1
# Let's get the 3rd row of the array
# 
array_2d[[2]]

array([[30, 35, 40]])

In [82]:
# Challenge 2
# Let's get the individual element 35
# using the format arr_2d[row][col] or arr_2d[row,col]
#
print(array_2d[2,1])

35


In [30]:
# Challenge 3
# Let's slice the array (2,2) from top right corner
# 

print(array_2d)
array_2d[0:2,1:]

[[15 20 25]
 [15 20 25]
 [30 35 40]]


array([[20, 25],
       [20, 25]])

In [34]:
# Challenge 4
# Let's create a random 6 x 4 matrix then select the 3rd and 4th rows
#

attribute_arr = np.random.rand(6,4)
print(attribute_arr)

attribute_arr[2:4,:]

[[0.02994363 0.30456849 0.46935604 0.25052863]
 [0.70623011 0.24264326 0.55707309 0.86694532]
 [0.50897823 0.3949881  0.45941871 0.51937322]
 [0.75772045 0.06456314 0.02301212 0.49733469]
 [0.59736413 0.78045602 0.86065154 0.14445318]
 [0.03825587 0.00330497 0.48151611 0.28433965]]


array([[0.50897823, 0.3949881 , 0.45941871, 0.51937322],
       [0.75772045, 0.06456314, 0.02301212, 0.49733469]])

## 1.4 Conditional Selection

In [100]:
# We can use conditions to check for whether elements in a certain range satisfy a condition.
# Let's first creating an array. Do you remember what the arrange function does?
#
conditional_arr = np.arange(1,11)
print(conditional_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [101]:
# Example 1  
# What do we do here?
#
conditional_arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [102]:
# Example 2
# What happens here?
#
bool_arr = conditional_arr > 3
print(bool_arr)

print(conditional_arr[bool_arr])

[False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]


In [103]:
# Example 3
# Finally, let's select those values in our array that satisfy our condition
# 
print(conditional_arr[conditional_arr > 4])

[ 5  6  7  8  9 10]


### <font color="green">1.4 Challenges</font>

In [36]:
# Creating the array to be used below
#
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
# Challenge 1
# Get the 2nd row using conditional selection
#
r = np.where(x[:,0] == 3)
print(x[r])



[[3 4 5]]


In [128]:
# Challenge 2
# Which elements are greater than two?
#
print(x[x > 2])

[3 4 5 6 7 8]


In [135]:
# Challenge 3
# Get the array [7, 8] from the x array
# 

print(x[x>6])

[7 8]


## 1.5 Operations

In [140]:
# Creating the array that we will use below:
# 
a = np.arange(0,5)
print(a)

[0 1 2 3 4]


In [142]:
# Example 1
# Arithmetic Operations
# 
addition_arr = a + a
print(addition_arr)

subtration_arr = a - a
print(subtration_arr)

[0 2 4 6 8]
[0 0 0 0 0]


In [145]:
# Example 2
# Universal Array Functions
# 
# square root
sqr_arr = np.sqrt(a)
print(sqr_arr)


# exponential
exp_arr = np.exp(a)
print(exp_arr)

[0.         1.         1.41421356 1.73205081 2.        ]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


### <font color="green">1.5 Challenges</font>

In [149]:
# Challenge 1
# Raise the a array created above to the power of 2
#
power2 = np.power(a,2)
print(power2)

[ 0  1  4  9 16]


In [150]:
# Challenge 2
# Find the log of a using log(), 
# the Universal Array Functions
#
l = np.log(a)
print(l)

[      -inf 0.         0.69314718 1.09861229 1.38629436]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


In [43]:
# Challenge 3
# This of a dataset then determine where you can use the 
# numpy concepts that you learnt in this session?
# Then explain them to your peer.

d = np.ones((4,6))
#print(d)

e = d + d + d
#print(e)

#print(e[2])

a = np.random.rand(3,6)
print(a)

[[0.59211882 0.53793835 0.36723895 0.28082937 0.57480406 0.54426058]
 [0.98636392 0.79875195 0.64439292 0.11156551 0.51745274 0.28127384]
 [0.49430648 0.9669042  0.48486301 0.61520222 0.0645889  0.42363521]]


In [44]:
print(np.sqrt(a))

[[0.76949257 0.73344281 0.60600244 0.52993336 0.75815834 0.73774018]
 [0.99315856 0.89372924 0.80274088 0.33401424 0.71934188 0.53035256]
 [0.70306933 0.98331287 0.69632106 0.78434828 0.25414346 0.65087265]]


In [45]:
print(np.log(a))

[[-0.52404796 -0.62001132 -1.00174255 -1.27000803 -0.55372605 -0.60832714]
 [-0.01372991 -0.22470484 -0.43944662 -2.19314331 -0.65883707 -1.26842657]
 [-0.70459955 -0.03365586 -0.72388888 -0.48580426 -2.73971277 -0.85888255]]


In [46]:
print(a[1,2])

print(a[1:])

0.6443929152216992
[[0.98636392 0.79875195 0.64439292 0.11156551 0.51745274 0.28127384]
 [0.49430648 0.9669042  0.48486301 0.61520222 0.0645889  0.42363521]]


In [49]:
print(a)

[[0.59211882 0.53793835 0.36723895 0.28082937 0.57480406 0.54426058]
 [0.98636392 0.79875195 0.64439292 0.11156551 0.51745274 0.28127384]
 [0.49430648 0.9669042  0.48486301 0.61520222 0.0645889  0.42363521]]


In [48]:
#indexes rows and columns separately
print(a[[1,2],[1,4]])

[0.79875195 0.0645889 ]
